version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
      - PORT=5002
      - FRIGATE_DB_HOST=10.0.20.6
      - FRIGATE_DB_PORT=5433
      - FRIGATE_DB_NAME=frigate_db
      - FRIGATE_DB_USER=frigate
      - FRIGATE_DB_PASSWORD=frigate_secure_pass_2024
      - VIDEO_SERVER_URL=http://10.0.20.6:8000
    ports:
      - '5002:5002'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
